name: Deploy Furina Uwu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server via SSH Passwordd
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Check secrets
        run: |
          [ -z "${{ secrets.SSH_HOST }}" ] && echo "❌ SSH_HOST is missing!" || echo "✅ SSH_HOST OK"
          [ -z "${{ secrets.SSH_USERNAME }}" ] && echo "❌ SSH_USERNAME is missing!" || echo "✅ SSH_USERNAME OK"
          [ -z "${{ secrets.SSH_PASSWORD }}" ] && echo "❌ SSH_PASSWORD is missing!" || echo "✅ SSH_PASSWORD OK"


      - name: 📡 SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 19019
          script: |
            cd ~/furina-bot
            git pull origin main
            docker-compose up --build -d
