name: Deploy Furina Uwu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server via SSH Passwordd
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Check if SSH_HOST is set
        run: |
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ SSH_HOST is missing!"
            exit 1
          else
            echo "✅ SSH_HOST is set."
          fi

      - name: 📡 SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 19019
          script: |
            cd ~/furina-bot
            git pull origin main
            docker-compose up --build -d
